version: '3.8'

services:
  app:
    build: .
    container_name: global-news-hub-app
    ports:
      - "8080:8080"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Load balancer configuration for local testing
  loadbalancer:
    image: haproxy:alpine
    container_name: global-news-hub-lb
    ports:
      - "80:80"
      - "8404:8404"  # HAProxy stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app
    restart: unless-stopped

networks:
  default:
    name: global-news-hub-network
